AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-hello-goodbye

  Sample SAM Template. Single Lambda, many API

Globals:
  Function:
    Timeout: 3

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        HelloName:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: get
        Goodbye:
          Type: Api
          Properties:
            Path: /goodbye
            Method: get

  HelloFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: HelloFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref HelloFunction]]

Outputs:
  url:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}"
